---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-tracking-pu100-t3-config
  namespace: cern-cms-gpu-tracking
data:
  config.yaml: |
    train_data_dir: /data/pu100_t3/train
    val_data_dir: /data/pu100_t3/val

    train_subset: null
    val_subset: null

    model: transformer

    hidden_dim: 128
    num_layers: 6
    nhead: 16
    latent_dim: 64
    dropout: 0.1

    block_size: 32
    n_hashes: 4
    num_regions: 8
    num_w_per_dist: 8

    learning_rate: 5e-4
    weight_decay: 1e-4

    batch_size: 3

    epochs: 20
    num_workers: 4
    num_cpu_threads: 64

    scheduler_gamma: 0.5
    early_stopping_patience: 20

    gradient_clip_val: 1.0
    gradient_clip_algorithm: norm

    accumulate_grad_batches: 4
    precision: 32

    output_dir: /data/output/pu100_t3/
    save_every: 5
    resume: null

    seed: 42

    oc_repulsive_chunk_size: 8
    oc_use_checkpointing: false

    oc_q_min: 0.1
    oc_s_B: 1.0

    gpus: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-tracking-pu100-t3
  namespace: cern-cms-gpu-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-tracking-pu100-t3
  template:
    metadata:
      labels:
        app: ml-tracking-pu100-t3
    spec:
      containers:
      - name: ml-tracking-pu100-t3-container
        image: aaarora/ml-tracking:latest
  #        args: ["python3", "src/main.py", "--config", "/home/config.yaml"]
  args: ["python3", "analysis/main.py", "--output", "/data/output/pu100_t3/run_05/", "--config", "/home/config.yaml", "--epsilon", "0.05"]
        resources:
          limits:
            memory: 32Gi
            cpu: 12
            nvidia.com/a100: 1
          requests:
            memory: 16Gi
            cpu: 8  
            nvidia.com/a100: 1
        volumeMounts:
        - mountPath: /data
          name: ml-tracking-pu100-t3-pvc
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /home/config.yaml
          subPath: config.yaml
          name: ml-tracking-pu100-t3-config-volume
      volumes:
        - name: ml-tracking-pu100-t3-pvc
          persistentVolumeClaim:
            claimName: ml-tracking-pvc
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
        - name: ml-tracking-pu100-t3-config-volume
          configMap:
            name: ml-tracking-pu100-t3-config
      restartPolicy: Always
