---
apiVersion: v1
kind: Pod
metadata:
  name: ml-tracking-tensorboard
  namespace: cern-cms-gpu-tracking
  labels:
    app: ml-tracking-tensorboard
spec:
  containers:
  - name: tensorboard
    image: aaarora/tensorboard:latest
    ports:
    - containerPort: 6006
      name: tensorboard
      protocol: TCP
    - containerPort: 8080
      name: nginx
      protocol: TCP
    resources:
      limits:
        memory: 1Gi
        cpu: 1
      requests:
        memory: 1Gi
        cpu: 1
    volumeMounts:
    - mountPath: /data
      name: ml-tracking-pvc
  volumes:
    - name: ml-tracking-pvc
      persistentVolumeClaim:
        claimName: ml-tracking-pvc
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ml-tracking-tensorboard
  namespace: cern-cms-gpu-tracking
spec:
  type: ClusterIP
  ports:
  - port: 6006
    targetPort: 6006
    protocol: TCP
    name: tensorboard
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: nginx
  selector:
    app: ml-tracking-tensorboard
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-tracking-tensorboard
  namespace: cern-cms-gpu-tracking
spec:
  ingressClassName: haproxy
  rules:
  - host: ml-tracking-tensorboard.nrp-nautilus.io
    http:
      paths:
      - backend:
          service:
            name: ml-tracking-tensorboard
            port:
              number: 6006
        path: /
        pathType: ImplementationSpecific
  - host: ml-tracking-files.nrp-nautilus.io
    http:
      paths:
      - backend:
          service:
            name: ml-tracking-tensorboard
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - ml-tracking-tensorboard.nrp-nautilus.io
    - ml-tracking-files.nrp-nautilus.io
